# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '40 10 * * *'
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies and Run
      run: |
        cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        python -m pip install --upgrade pip
        pip install requests xlwt
        python Publish_Monitor.py
    - name: Commit 
      run: |
        git config --global user.email Publish_Monitor@email.com
        git config --global user.name Publish_Monitor
        git add .
        git commit -m "update new xls" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
